// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace SPRTechforgetestproject.Features.Financefuture
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Featurefileofchatgpt")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class FeaturefileofchatgptFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Financefuture", "Featurefileofchatgpt", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Featurefileofchatgpt.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Financefuture/Featurefileofchatgpt.feature.ndjson", 26);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Tc_01 Verify user can save Ledgeraccount record")]
        [global::NUnit.Framework.CategoryAttribute("Regression")]
        [global::NUnit.Framework.TestCaseAttribute("Ajay", "Bank", "sbi", "50000", "0", "16-12-2025", "Personal savings account", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("ram", "Cash", "hdfc", "100000", "0", "16-12-2025", "Business current account", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("kalyan", "Debtor", "icici", "30000", "0", "16-12-2025", "Monthly salary account", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("mahesh", "Creditor", "bajaj", "20000", "0", "16-12-2025", "Office expense account", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("veeru", "Expense", "indus", "20000", "5000", "17-12-2025", "loan account", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("Rohit", "Salary", "canara", "80000", "7000", "16-12-2025", "Monthly salary account", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("sachin", "Income", "kotak", "60000", "0", "17-12-2025", "Freelance income account", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("Rahul", "Equity", "yesbank", "40000", "0", "16-12-2025", "Investment account", "7", null)]
        public async global::System.Threading.Tasks.Task Tc_01VerifyUserCanSaveLedgeraccountRecord(string name, string accounttype, string subledger, string openingbalence, string fixedmonthlyamount, string startdate, string description, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Regression"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("Accounttype", accounttype);
            argumentsOfScenario.Add("subledger", subledger);
            argumentsOfScenario.Add("openingbalence", openingbalence);
            argumentsOfScenario.Add("Fixedmonthlyamount", fixedmonthlyamount);
            argumentsOfScenario.Add("startdate", startdate);
            argumentsOfScenario.Add("Description", description);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tc_01 Verify user can save Ledgeraccount record", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
   this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await testRunner.GivenAsync("user navigate to login page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
  await testRunner.WhenAsync("user clicks Finance module", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 7
  await testRunner.AndAsync("user click on Legder Accounts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
  await testRunner.AndAsync("user click Add Account", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
  await testRunner.AndAsync(string.Format("user fills details with \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\" \"{5}\" \"{6}\"", name, accounttype, subledger, openingbalence, fixedmonthlyamount, startdate, description), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
  await testRunner.AndAsync("user click on save account", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
  await testRunner.ThenAsync("Accounts added succesfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Tc_02 Verify user can save <Module> record")]
        [global::NUnit.Framework.CategoryAttribute("Regression")]
        [global::NUnit.Framework.TestCaseAttribute("Income", "16-12-2025", "10000", "Gudari (1)", "Ajay [Bank]", "Advance payment", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("Expense", "16-12-2025", "15000", "Ajay [Bank]", "Rohit [Salary]", "Stationary purchase", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("Transfer", "16-12-2025", "20000", "Ajay [Bank]", "ram [Cash]", "Salary transfer", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("Refund", "16-12-2025", "50000", "ram [Cash]", "Gudari (1)", "Refund to candidate", "11", null)]
        public async global::System.Threading.Tasks.Task Tc_02VerifyUserCanSaveModuleRecord(string module, string date, string amount, string from, string to, string description, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Regression"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Module", module);
            argumentsOfScenario.Add("Date", date);
            argumentsOfScenario.Add("Amount", amount);
            argumentsOfScenario.Add("From", from);
            argumentsOfScenario.Add("To", to);
            argumentsOfScenario.Add("Description", description);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tc_02 Verify user can save <Module> record", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 26
    await testRunner.GivenAsync("user navigate to login page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
    await testRunner.WhenAsync("user clicks Finance module", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
    await testRunner.AndAsync("user click on Payroll", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
 await testRunner.AndAsync("user clicks payexpance module", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
    await testRunner.AndAsync(string.Format("user selects {0} page", module), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
    await testRunner.AndAsync(string.Format("user fills details with \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\"", date, amount, from, to, description), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
    await testRunner.ThenAsync("record should be saved successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Tc_03 Verify user can check on  Transactions save or Not")]
        [global::NUnit.Framework.CategoryAttribute("Regression")]
        [global::NUnit.Framework.TestCaseAttribute("Advance payment", "Income", "Unlocked", "Gudari (1)", "Ajay", "16-12-2025", "16-12-2025", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("Stationary purchase", "Expense", "Unlocked", "Ajay", "Rohit [Salary]", "16-12-2025", "16-12-2025", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("Salary transfer", "Transfer", "Unlocked", "ram", "Ajay", "16-12-2025", "16-12-2025", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("Refund to candidate", "Refund", "Unlocked", "ram", "Gudari (1)", "16-12-2025", "16-12-2025", "15", null)]
        public async global::System.Threading.Tasks.Task Tc_03VerifyUserCanCheckOnTransactionsSaveOrNot(string description, string types, string statuses, string sourceFrom, string destinationTo, string fromdate, string todate, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Regression"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Description", description);
            argumentsOfScenario.Add("Types", types);
            argumentsOfScenario.Add("Statuses", statuses);
            argumentsOfScenario.Add("SourceFrom", sourceFrom);
            argumentsOfScenario.Add("DestinationTo", destinationTo);
            argumentsOfScenario.Add("Fromdate", fromdate);
            argumentsOfScenario.Add("Todate", todate);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tc_03 Verify user can check on  Transactions save or Not", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 46
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 47
    await testRunner.GivenAsync("user navigate to login page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 48
    await testRunner.WhenAsync("user clicks Finance module", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
    await testRunner.AndAsync("user click on Transactions", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
 await testRunner.AndAsync(string.Format("user fill details with \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\" \"{5}\" \"{6}\"", description, types, statuses, sourceFrom, destinationTo, fromdate, todate), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Tc_04 Verify user can check on  LedgerAccounts")]
        [global::NUnit.Framework.CategoryAttribute("Regression")]
        [global::NUnit.Framework.TestCaseAttribute("Ajay", "16", null)]
        [global::NUnit.Framework.TestCaseAttribute("ram", "17", null)]
        [global::NUnit.Framework.TestCaseAttribute("kalyan", "18", null)]
        [global::NUnit.Framework.TestCaseAttribute("mahesh", "19", null)]
        [global::NUnit.Framework.TestCaseAttribute("veeru", "20", null)]
        [global::NUnit.Framework.TestCaseAttribute("Rohit", "21", null)]
        [global::NUnit.Framework.TestCaseAttribute("sachin", "22", null)]
        [global::NUnit.Framework.TestCaseAttribute("Rahul", "23", null)]
        public async global::System.Threading.Tasks.Task Tc_04VerifyUserCanCheckOnLedgerAccounts(string searchby, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Regression"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Searchby", searchby);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tc_04 Verify user can check on  LedgerAccounts", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 62
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 63
    await testRunner.GivenAsync("user navigate to login page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 64
    await testRunner.WhenAsync("user clicks Finance module", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 65
    await testRunner.AndAsync("user click on Legder Accounts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
    await testRunner.ThenAsync(string.Format("user search by name or sub-type \"{0}\"", searchby), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
