// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace SPRTechforgetestproject.Features.Candidatelistfuture
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Candidate Registration")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class CandidateRegistrationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Candidatelistfuture", "Candidate Registration", "user is checking of candidate list", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Feature.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Candidatelistfuture/Feature.feature.ndjson", 5);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Tc_01_Add a candidate with different statuses")]
        [global::NUnit.Framework.TestCaseAttribute("Gudari", "1", "8499020987", "1234567890", "gudari.qa@gmail.com", "someone", "KPHB", "No Support", "16-12-2025", "30000", "300000", "100000", "Ready for Interview", "Candidate remarks added", "16-12-2025", "gudari", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("Ramesh", "2", "9998887776", "8889997776", "ramesh@gmail.com", "someone", "Hyderabad", "Active Support (Monthly Billing)", "16-12-2025", "30000", "300000", "100000", "Ready for Interview", "Candidate remarks added", "16-12-2025", "ramesh", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("Suresh", "3", "9876543210", "8765432109", "suresh@gmail.com", "someone", "Kukatpally", "Support Ended", "16-12-2025", "30000", "300000", "100000", "Ready for Interview", "Candidate remarks added", "16-12-2025", "suresh", "2", null)]
        public async global::System.Threading.Tasks.Task Tc_01_AddACandidateWithDifferentStatuses(
                    string name, 
                    string iD, 
                    string phone1, 
                    string phone2, 
                    string email, 
                    string refferdby, 
                    string address, 
                    string supportstatus, 
                    string startdate, 
                    string amount, 
                    string agreedtotalamount, 
                    string totalpaid, 
                    string status, 
                    string notes, 
                    string date, 
                    string signature, 
                    string @__pickleIndex, 
                    string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("ID", iD);
            argumentsOfScenario.Add("Phone1", phone1);
            argumentsOfScenario.Add("Phone2", phone2);
            argumentsOfScenario.Add("Email", email);
            argumentsOfScenario.Add("Refferdby", refferdby);
            argumentsOfScenario.Add("Address", address);
            argumentsOfScenario.Add("supportstatus", supportstatus);
            argumentsOfScenario.Add("startdate", startdate);
            argumentsOfScenario.Add("Amount", amount);
            argumentsOfScenario.Add("Agreedtotalamount", agreedtotalamount);
            argumentsOfScenario.Add("totalpaid", totalpaid);
            argumentsOfScenario.Add("Status", status);
            argumentsOfScenario.Add("Notes", notes);
            argumentsOfScenario.Add("Date", date);
            argumentsOfScenario.Add("Signature", signature);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tc_01_Add a candidate with different statuses", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 3
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
    await testRunner.GivenAsync("the user opens the website and logs in", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 5
    await testRunner.AndAsync("the user navigates to add candidate page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 6
 await testRunner.WhenAsync(string.Format("the user enter \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\" \"{5}\" \"{6}\" \"{7}\" \"{8}\" \"{9}\" \"{10}\"" +
                            " \"{11}\" \"{12}\" \"{13}\" \"{14}\" \"{15}\"", name, iD, phone1, phone2, email, refferdby, address, supportstatus, startdate, amount, agreedtotalamount, totalpaid, status, notes, date, signature), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 7
    await testRunner.AndAsync("the user saves the candidate", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
    await testRunner.ThenAsync("the candidate should be added with correct status", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
